baseURL = 'https://glaforge.dev/'
languageCode = 'en-us'
title = 'Guillaume Laforge'
theme = 'glaforge-from-blank'
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
pagination.pagerSize = 10
enableRobotsTXT = true
enableEmoji = true

[params]
description = 'Tech blog of Guillaume Laforge, with articles on generative AI, LLMs, cloud computing, microservices architecture, serverless solutions, Java and Apache Groovy programming'
[params.social]
twitter = '@glaforge'
twitterURL = 'https://twitter.com/@glaforge'
mastodon = '@uwyn.net@glaforge'
mastodonURL = 'https://uwyn.net/@glaforge'
bluesky = 'glaforge.dev'
blueskyURL = 'https://bsky.app/profile/glaforge.dev'
linkedin = 'glaforge'
linkedinURL = 'https://linkedin.com/in/glaforge'
github = 'glaforge'
githubURL = 'https://github.com/glaforge'
speakerdeck = 'glaforge'
speakerdeckURL = 'https://speakerdeck.com/glaforge'

[menu]
[[menu.main]]
identifier = 'Home'
name = 'BLOG'
title = 'Blog'
url = '/'
weight = 10
[[menu.main]]
identifier = 'Talks'
name = 'TALKS'
title = 'Talks'
url = '/talks'
weight = 40
[[menu.main]]
identifier = 'About'
name = 'ABOUT'
title = 'About'
url = '/about'
weight = 50

[author]
name = 'Guillaume Laforge'

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'friendly'
tabWidth = 4

[markup.goldmark.renderer]
xhtml = true
unsafe = true

[sitemap]
changefreq = 'daily'

[outputFormats.llms]
baseName = "llms"
mediaType = "text/plain"
isPlainText = true

[outputFormats.llms-full]
baseName = "llms-full"
mediaType = "text/plain"
isPlainText = true

[outputs]
home = ["HTML", "RSS", "llms", "llms-full"]
